
typedef enum AssetTexture {
	ASSET_TEXTURE_WALL,
	ASSET_TEXTURE_COUNTER,
	ASSET_TEXTURE_DWARF0,
	ASSET_TEXTURE_DWARF1,
	ASSET_TEXTURE_OGRE0,
	ASSET_TEXTURE_OGRE1,
	ASSET_TEXTURE_LADY0,
	ASSET_TEXTURE_LADY1,
	ASSET_TEXTURE_CREEPYMAN0,
	ASSET_TEXTURE_THINKING,
	ASSET_TEXTURE_SPEECH,
	ASSET_TEXTURE_SPEECH_INTRO0,
	ASSET_TEXTURE_HAND0,
	ASSET_TEXTURE_HAND1,
	ASSET_TEXTURE_HAND0_TRAIL,
	ASSET_TEXTURE_HAND1_TRAIL,
	ASSET_TEXTURE_SHRINE0,
	ASSET_TEXTURE_SHRINE1,
	ASSET_TEXTURE_SHRINE2,
	ASSET_TEXTURE_SUMMON_BOOK,
	ASSET_TEXTURE_CHICKEN_GRAPHIC,
	ASSET_TEXTURE_SHEEP_GRAPHIC,
	ASSET_TEXTURE_CHICKEN0,
	ASSET_TEXTURE_CHICKEN1,
	ASSET_TEXTURE_CHICKEN2,
	ASSET_TEXTURE_RCHICKEN0,
	ASSET_TEXTURE_BRCHICKEN0,
	ASSET_TEXTURE_SHEEP0,
	ASSET_TEXTURE_RLAMB,
	ASSET_TEXTURE_BRLAMB,
	ASSET_TEXTURE_METER_BOTTOM,
	ASSET_TEXTURE_METER_TOP,
	ASSET_TEXTURE_BUTTON_X,
	ASSET_TEXTURE_BUTTON_CIRCLE,
	ASSET_TEXTURE_GOLD_ICON,
	ASSET_TEXTURE_CREEP_INTRO,
	ASSET_TEXTURE_COUNT,
} AssetTexture;

typedef enum AssetSound {
	ASSET_SOUND_CHICKEN_SUMMON,
	ASSET_SOUND_CHICKEN_DEAD,
	ASSET_SOUND_BURNING,
	ASSET_SOUND_WOOSH,
	ASSET_SOUND_CRUNCH,
	ASSET_SOUND_COIN0,
	ASSET_SOUND_COIN1,
	ASSET_SOUND_COIN2,
	ASSET_SOUND_SHEEP_SUMMON,
	ASSET_SOUND_SHEEP_DEAD,
	ASSET_SOUND_COUNT,
} AssetSound;

typedef enum AssetMusic {
	ASSET_MUSIC_CREEPY_INTRO,
	ASSET_MUSIC_PLAYING,
	ASSET_MUSIC_COUNT,
} AssetMusic;

void AssetsInit(void);
void AssetsDeinit(void);

Texture2D AssetsGetTexture(AssetTexture texture);
Sound AssetsGetSound(AssetSound sound);
Font AssetsGetFont(void);
Music AssetsGetMusic(AssetMusic music);
