
typedef enum AssetTexture {
	ASSET_TEXTURE_WALL,
	ASSET_TEXTURE_COUNTER,
	ASSET_TEXTURE_DWARF0,
	ASSET_TEXTURE_OGRE0,
	ASSET_TEXTURE_LADY0,
	ASSET_TEXTURE_THINKING,
	ASSET_TEXTURE_SPEECH,
	ASSET_TEXTURE_HAND0,
	ASSET_TEXTURE_HAND1,
	ASSET_TEXTURE_HAND0_TRAIL,
	ASSET_TEXTURE_HAND1_TRAIL,
	ASSET_TEXTURE_SHRINE0,
	ASSET_TEXTURE_SHRINE1,
	ASSET_TEXTURE_SHRINE2,
	ASSET_TEXTURE_SUMMON_BOOK,
	ASSET_TEXTURE_CHICKEN_GRAPHIC,
	ASSET_TEXTURE_CHICKEN0,
	ASSET_TEXTURE_CHICKEN1,
	ASSET_TEXTURE_CHICKEN2,
	ASSET_TEXTURE_RCHICKEN0,
	ASSET_TEXTURE_BRCHICKEN0,
	ASSET_TEXTURE_BUTTON_X,
	ASSET_TEXTURE_BUTTON_CIRCLE,
	ASSET_TEXTURE_COUNT,
} AssetTexture;

void AssetsInit(void);
void AssetsDeinit(void);

Texture2D AssetsGetTexture(AssetTexture texture);

Font AssetsGetFont(void);
